on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment you want to rollback'
        required: true
        default: 'production'

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v5
      with:
        script: |
          const result = await github.request('GET /repos/{owner}/{repo}/deployments', {
                                  owner: context.repo.owner,
                                  repo: context.repo.repo
                                })

          const filtered_result = result.data.filter(deployment => deployment.environment === ' ${{ github.event.inputs.environment }}')
          console.log(filtered_result)